const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);let stream, facing='environment', photoURL='';
function show(id){$$('.page').forEach(x=>x.classList.remove('active'));$('#'+id+'Page').classList.add('active');$('.bottom-nav').style.display=(id==='splash'||id==='login'||id==='signup')?'none':'flex';$('.topbar').style.display=(id==='home')?'flex':'none';$$('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.go===id));if(id==='capture')startCamera();else stopCamera();window.scrollTo(0,0)}
$$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));$('#settingsButton').onclick=()=>show('settings');$('#loginButton').onclick=()=>{show('home');toast('환영합니다!')};$('#googleLogin').onclick=()=>{show('home');toast('Google 로그인 베타가 완료됐어요!')};$('#guestLogin').onclick=()=>{show('home');toast('게스트로 시작했어요. 기록은 이 기기에 저장됩니다.')};$('.signup-submit').onclick=()=>{show('home');toast('가입이 완료됐어요!')};
$('#mapPage').insertAdjacentHTML('beforeend','<div class="embedded-banakpo"><div class="embed-title"><b>바낚포 낚시 포인트</b><span>외부 지도 직접 표시</span></div><iframe title="바낚포 낚시 포인트 지도" src="https://www.banakpo.co.kr/frame/webMain.do" loading="lazy"></iframe><p>사이트 정책에 따라 화면이 차단될 경우 아래 버튼을 이용하세요.</p></div>');
async function startCamera(){if(photoURL)return;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:facing},audio:false});$('#camera').srcObject=stream;$('#camera').style.display='block';$('#cameraEmpty').style.display='none'}catch(e){$('#cameraEmpty').innerHTML='<span>▧</span><b>카메라 권한이 필요합니다</b><small>브라우저 설정에서 카메라를 허용하거나 갤러리에서 사진을 선택하세요.</small>'}}
function stopCamera(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}}
function setPhoto(url){photoURL=url;$('#preview').src=url;$('#analysisImage').src=url;$('#preview').style.display='block';$('#camera').style.display='none';$('#cameraEmpty').style.display='none';$('#analyzeButton').disabled=false;$('#analyzeButton').classList.remove('disabled');stopCamera()}
$('#shutter').onclick=()=>{if(!stream)return;const c=document.createElement('canvas'),v=$('#camera');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);setPhoto(c.toDataURL('image/jpeg',.9))};
$('#galleryButton').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{const f=e.target.files[0];if(f)setPhoto(URL.createObjectURL(f))};$('#flipCamera').onclick=()=>{facing=facing==='environment'?'user':'environment';stopCamera();startCamera()};
$('#analyzeButton').onclick=()=>{if(photoURL){show('analysis');toast('AI가 어종과 측정 눈금을 분석했어요.')}};$('#submitRecord').onclick=()=>{show('ranking');toast('공식 기록이 등록되어 일간 랭킹 2위에 올랐어요!')};
setTimeout(()=>{$('#emailLogin').onclick=()=>{$('#emailLoginModal').classList.add('open');$('#emailLoginModal').setAttribute('aria-hidden','false');$('#emailLoginEmail').focus()};$('#closeEmailLogin').onclick=()=>{$('#emailLoginModal').classList.remove('open');$('#emailLoginModal').setAttribute('aria-hidden','true')};$('#emailLoginModal').onclick=e=>{if(e.target===$('#emailLoginModal'))$('#closeEmailLogin').click()};$('#emailLoginSubmit').onclick=async()=>{const email=$('#emailLoginEmail').value.trim(),password=$('#emailLoginPassword').value;if(!email||!password){toast('Enter email and password.');return}try{await window.fishonData.signInWithEmail(email,password);$('#closeEmailLogin').click();show('home');toast('Logged in. Your profile was saved.')}catch(error){toast(error.code==='auth/invalid-credential'?'Incorrect email or password.':'Login failed.')}}},0);
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2700)}
$('#handChoice').onclick=e=>{if(e.target.tagName!=='BUTTON')return;$$('#handChoice button').forEach(x=>x.classList.remove('selected'));e.target.classList.add('selected');$('#app').classList.toggle('left-hand',e.target.dataset.hand==='left')};
$('#fontChoice').onclick=e=>{if(e.target.tagName!=='BUTTON')return;$$('#fontChoice button').forEach(x=>x.classList.remove('selected'));e.target.classList.add('selected');$('#app').classList.remove('font-serif','font-round');if(e.target.dataset.font!=='sans')$('#app').classList.add('font-'+e.target.dataset.font)};
$('#periodTabs').onclick=e=>{if(e.target.tagName!=='BUTTON')return;$$('#periodTabs button').forEach(x=>x.classList.remove('selected'));e.target.classList.add('selected');toast(e.target.textContent+' 랭킹을 불러왔어요.')};
$('#splashPage').onclick=()=>show('home');$('.home-banakpo')?.remove();var banakpoPromo=$('#mapPage .banakpo-link');if(banakpoPromo){banakpoPromo.className='banakpo-promo';banakpoPromo.innerHTML='<span class="promo-icon">🎣</span><span class="promo-copy"><small>BUSAN FISHING PARTNER</small><b>바낚포에서 더 많은 낚시 포인트 찾기</b><em>방파제 · 갯바위 · 조황 정보까지 한 번에</em></span><strong>↗</strong>'}
$('.embedded-banakpo')?.remove();$('.banakpo-promo')?.remove();var fishingPoints=[['송정 동쪽 방파제','감성돔 · 벵에돔','35.179','129.201','18%','25%'],['기장 길천 방파제','감성돔 · 숭어','35.313','129.270','11%','48%'],['기장 학리 방파제','우럭 · 감성돔','35.321','129.276','17%','64%'],['가덕도 천성항','광어 · 우럭','35.024','128.830','67%','76%']];var mapShell=$('.google-map');if(mapShell){mapShell.insertAdjacentHTML('beforeend',fishingPoints.map((p,i)=>'<a class="map-point-pin" style="left:'+p[4]+';top:'+p[5]+'" href="https://www.google.com/maps/search/?api=1&query='+p[2]+','+p[3]+'" target="_blank" rel="noopener"><i>'+String(i+1)+'</i><span>'+p[0]+'</span></a>').join(''));mapShell.insertAdjacentHTML('afterend','<section class="point-directory"><div class="directory-head"><span>BUSAN POINTS</span><b>부산 낚시 포인트</b><small>4곳</small></div>'+fishingPoints.map((p,i)=>'<a class="point-row" href="https://www.google.com/maps/search/?api=1&query='+p[2]+','+p[3]+'" target="_blank" rel="noopener"><span class="point-number">'+String(i+1)+'</span><span><b>'+p[0]+'</b><small>'+p[1]+'</small></span><em>지도 보기 ↗</em></a>').join('')+'</section>')}
$('#splashPage').onclick=()=>show('login');$('#googleLogin').onclick=async()=>{if(window.fishonData){try{await window.fishonData.signInGoogle();show('home');toast('Google 로그인 완료!')}catch(e){toast('로그인을 취소했어요.')}}else{show('home');toast('Firebase 연결 전 베타 로그인입니다.')}};$('#guestLogin').onclick=async()=>{if(window.fishonData){try{await window.fishonData.signInGuest();show('home');toast('게스트 모드로 시작했어요.')}catch(e){toast('게스트 로그인을 시작할 수 없어요.')}}else{show('home');toast('게스트 모드로 시작했어요.')}};
$('#submitRecord').onclick=async()=>{const lengthCm=Number($('#lengthInput').value);try{if(window.fishonData&&window.fishonUser){await window.fishonData.saveCatch({userId:window.fishonUser.uid,species:'감성돔',lengthCm,area:'부산 송정권',verified:true});}show('ranking');toast('공식 기록이 등록됐어요!')}catch(e){toast('기록 저장에 실패했어요.')}};
$('.signup-submit').onclick=async()=>{const nickname=$('#signupNickname').value.trim(),email=$('#signupEmail').value.trim(),password=$('#signupPassword').value;if(!nickname||!email||password.length<8){toast('닉네임, 이메일과 8자 이상 비밀번호를 입력해주세요.');return}if(!window.fishonData){toast('Firebase 연결을 확인해주세요.');return}try{const result=await window.fishonData.signUpWithEmail(email,password);await window.fishonData.saveUserProfile(result.user,{nickname,email,createdAt:new Date().toISOString()});show('home');toast('회원가입과 로그인이 완료됐어요!')}catch(error){const messages={'auth/email-already-in-use':'이미 가입된 이메일이에요.','auth/invalid-email':'이메일 형식을 확인해주세요.','auth/weak-password':'비밀번호는 8자 이상으로 입력해주세요.','auth/operation-not-allowed':'이메일 로그인 설정이 아직 활성화되지 않았어요.'};toast(messages[error.code]||'회원가입에 실패했어요.')}};
$('#emailLogin').onclick=async()=>{const email=prompt('가입한 이메일을 입력해주세요.');if(!email)return;const password=prompt('비밀번호를 입력해주세요.');if(!password)return;try{await window.fishonData.signInWithEmail(email,password);show('home');toast('로그인됐어요!')}catch(error){toast(error.code==='auth/invalid-credential'?'이메일 또는 비밀번호가 맞지 않아요.':'로그인에 실패했어요.')}};
