const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);let stream, facing='environment', photoURL='';
function show(id){$$('.page').forEach(x=>x.classList.remove('active'));$('#'+id+'Page').classList.add('active');$('.bottom-nav').style.display=(id==='splash'||id==='login'||id==='signup')?'none':'flex';$('.topbar').style.display=(id==='home')?'flex':'none';$$('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.go===id));if(id==='capture')startCamera();else stopCamera();window.scrollTo(0,0)}
$$('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));$('#settingsButton').onclick=()=>show('settings');$('#loginButton').onclick=()=>{show('home');toast('환영합니다!')};$('#googleLogin').onclick=()=>{show('home');toast('Google 로그인 베타가 완료됐어요!')};$('#guestLogin').onclick=()=>{show('home');toast('게스트로 시작했어요. 기록은 이 기기에 저장됩니다.')};$('.signup-submit').onclick=()=>{show('home');toast('가입이 완료됐어요!')};
async function startCamera(){if(photoURL)return;try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:facing},audio:false});$('#camera').srcObject=stream;$('#camera').style.display='block';$('#cameraEmpty').style.display='none'}catch(e){$('#cameraEmpty').innerHTML='<span>▧</span><b>카메라 권한이 필요합니다</b><small>브라우저 설정에서 카메라를 허용하거나 갤러리에서 사진을 선택하세요.</small>'}}
function stopCamera(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}}
function setPhoto(url){photoURL=url;$('#preview').src=url;$('#analysisImage').src=url;$('#preview').style.display='block';$('#camera').style.display='none';$('#cameraEmpty').style.display='none';$('#analyzeButton').disabled=false;$('#analyzeButton').classList.remove('disabled');stopCamera()}
$('#shutter').onclick=()=>{if(!stream)return;const c=document.createElement('canvas'),v=$('#camera');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);setPhoto(c.toDataURL('image/jpeg',.9))};
$('#galleryButton').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{const f=e.target.files[0];if(f)setPhoto(URL.createObjectURL(f))};$('#flipCamera').onclick=()=>{facing=facing==='environment'?'user':'environment';stopCamera();startCamera()};
$('#analyzeButton').onclick=()=>{if(photoURL){show('analysis');toast('AI가 어종과 측정 눈금을 분석했어요.')}};$('#submitRecord').onclick=()=>{show('ranking');toast('공식 기록이 등록되어 일간 랭킹 2위에 올랐어요!')};
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2700)}
$('#handChoice').onclick=e=>{if(e.target.tagName!=='BUTTON')return;$$('#handChoice button').forEach(x=>x.classList.remove('selected'));e.target.classList.add('selected');$('#app').classList.toggle('left-hand',e.target.dataset.hand==='left')};
$('#fontChoice').onclick=e=>{if(e.target.tagName!=='BUTTON')return;$$('#fontChoice button').forEach(x=>x.classList.remove('selected'));e.target.classList.add('selected');$('#app').classList.remove('font-serif','font-round');if(e.target.dataset.font!=='sans')$('#app').classList.add('font-'+e.target.dataset.font)};
$('#periodTabs').onclick=e=>{if(e.target.tagName!=='BUTTON')return;$$('#periodTabs button').forEach(x=>x.classList.remove('selected'));e.target.classList.add('selected');toast(e.target.textContent+' 랭킹을 불러왔어요.')};
